[package]
name = "minesweeper-rs"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2018"

[dependencies]
windows = "0.12.0"
bindings = { path = "bindings" }
winit = "0.24.0"
raw-window-handle = "0.3.3"
rand = "0.8.3"

[features]
show-mines = []
